### ISSUE TITLE
Mirror source are not working

### ISSUE THREAD

**Issue by Light7654** [Stormunblessed/CloudStream-3#1]
**Guidelines:**
- [x] It **is not** a duplicate issue.
- [x] If related to a provider, I have checked the site and it works, but not the app.

**To Reproduce**

**Expected behavior**
When play say's no link found

**Screenshots or video**

**Device (please complete the following information):**
 - Android Version: [Android 8.1.0] 
 - App Version: [v2.8.0 PRE]
 - Provider: [yesmovies, Fmovies]

**Additional context**

**Comment by Stormunblessed** [comment]
If it doesn't work in [original](https://github.com/LagradOst/CloudStream-3), then I can't do anything
