### ISSUE TITLE
Select 1080p by default in crunchyroll

### ISSUE THREAD

**Issue by venkat2305** [Stormunblessed/CloudStream-3#11]
![Screenshot_2022-07-26-18-49-00-826_com.stormunblessed.cloudstream3.prerelease.jpg](https://user-images.githubusercontent.com/55329452/181015882-7f051993-bf52-4adf-9fa5-f39a65e11048.jpg)

By default it's selecting 480p and we have to change quality for every single episode. Please fix this.

Also, there's no mention of quality in the sources of crunchyroll. Please fix this

**Comment by ghost** [comment]
@venkat2305 It's not possible, I have tried
