### ISSUE TITLE
Provider request

### ISSUE THREAD

**Issue by altCK129** [Stormunblessed/CloudStream-3#3]
Can you add an indian provider please .
Example : https://filmyzilla.beauty/ 
https://worldfree4u.wine/
You can add some other indian website too if you know any . Thanx

**Comment by Stormunblessed** [comment]
You should go to https://github.com/LagradOst/CloudStream-3 if you want to request sites, I made this fork to add providers that I will use

**Comment by krrishkap** [comment]
Ok
